ALTER TABLE cards ADD COLUMN card_number INT AFTER flavor_text;
ALTER TABLE cards ADD CONSTRAINT UNIQUE KEY (expansionset_id, card_number);

ALTER TABLE expansionsets ADD COLUMN abbr CHAR(6) AFTER name;
UPDATE expansionsets SET abbr = 'LEA' WHERE name = 'Alpha';
UPDATE expansionsets SET abbr = 'BTD' WHERE name = 'Beatdown Box Set';
UPDATE expansionsets SET abbr = 'LEB' WHERE name = 'Beta';
UPDATE expansionsets SET abbr = 'DKA' WHERE name = 'Dark Ascension';
UPDATE expansionsets SET abbr = 'DIS' WHERE name = 'Dissension';
UPDATE expansionsets SET abbr = 'DGM' WHERE name = 'Dragon''s Maze';
UPDATE expansionsets SET abbr = 'DDH' WHERE name = 'Duel Decks: Ajani vs. Nicol Bolas';
UPDATE expansionsets SET abbr = 'DDC' WHERE name = 'Duel Decks: Divine vs. Demonic';
UPDATE expansionsets SET abbr = '8ED' WHERE name = 'Eighth Edition';
UPDATE expansionsets SET abbr = 'EVE' WHERE name = 'Eventide';
UPDATE expansionsets SET abbr = 'EXO' WHERE name = 'Exodus';
UPDATE expansionsets SET abbr = '5DN' WHERE name = 'Fifth Dawn';
UPDATE expansionsets SET abbr = '4ED' WHERE name = 'Fourth Edition';
UPDATE expansionsets SET abbr = 'V11' WHERE name = 'From the Vault: Legends';
UPDATE expansionsets SET abbr = 'GTC' WHERE name = 'Gatecrash';
UPDATE expansionsets SET abbr = 'GPT' WHERE name = 'Guildpact';
UPDATE expansionsets SET abbr = 'ISD' WHERE name = 'Innistrad';
UPDATE expansionsets SET abbr = 'INV' WHERE name = 'Invasion';
UPDATE expansionsets SET abbr = 'LGN' WHERE name = 'Legions';
UPDATE expansionsets SET abbr = 'LEA' WHERE name = 'Limited Edition Alpha';
UPDATE expansionsets SET abbr = 'LEB' WHERE name = 'Limited Edition Beta';
UPDATE expansionsets SET abbr = 'LRW' WHERE name = 'Lorwyn';
UPDATE expansionsets SET abbr = 'M10' WHERE name = 'Magic 2010';
UPDATE expansionsets SET abbr = 'M11' WHERE name = 'Magic 2011';
UPDATE expansionsets SET abbr = 'M12' WHERE name = 'Magic 2012';
UPDATE expansionsets SET abbr = 'M13' WHERE name = 'Magic 2013';
UPDATE expansionsets SET abbr = 'M14' WHERE name = 'Magic 2014 Core Set';
UPDATE expansionsets SET abbr = 'CMD' WHERE name = 'Magic: The Gathering-Commander';
UPDATE expansionsets SET abbr = 'ME4' WHERE name = 'Masters Edition IV';
UPDATE expansionsets SET abbr = 'MMQ' WHERE name = 'Mercadian Masques';
UPDATE expansionsets SET abbr = 'jcME' WHERE name = 'Middle Earth';
UPDATE expansionsets SET abbr = 'MIR' WHERE name = 'Mirage';
UPDATE expansionsets SET abbr = 'MBS' WHERE name = 'Mirrodin Besieged';
UPDATE expansionsets SET abbr = 'MMA' WHERE name = 'Modern Masters';
UPDATE expansionsets SET abbr = 'MOR' WHERE name = 'Morningtide';
UPDATE expansionsets SET abbr = 'NPH' WHERE name = 'New Phyrexia';
UPDATE expansionsets SET abbr = '9ED' WHERE name = 'Ninth Edition';
UPDATE expansionsets SET abbr = 'HOP' WHERE name = 'Planechase';
UPDATE expansionsets SET abbr = 'PD2' WHERE name = 'Premium Deck Series: Fire and Lightning';
UPDATE expansionsets SET abbr = 'PD3' WHERE name = 'Premium Deck Series: Graveborn';
UPDATE expansionsets SET abbr = 'RAV' WHERE name = 'Ravnica: City of Guilds';
UPDATE expansionsets SET abbr = 'RTR' WHERE name = 'Return to Ravnica';
UPDATE expansionsets SET abbr = 'ROE' WHERE name = 'Rise of the Eldrazi';
UPDATE expansionsets SET abbr = 'SOM' WHERE name = 'Scars of Mirrodin';
UPDATE expansionsets SET abbr = 'SCG' WHERE name = 'Scourge';
UPDATE expansionsets SET abbr = '7ED' WHERE name = 'Seventh Edition';
UPDATE expansionsets SET abbr = 'ALA' WHERE name = 'Shards of Alara';
UPDATE expansionsets SET abbr = '2ED' WHERE name = 'Unlimited Edition';
UPDATE expansionsets SET abbr = 'UDS' WHERE name = 'Urza''s Destiny';
UPDATE expansionsets SET abbr = 'ULG' WHERE name = 'Urza''s Legacy';
UPDATE expansionsets SET abbr = 'VIS' WHERE name = 'Visions';
UPDATE expansionsets SET abbr = 'WTH' WHERE name = 'Weatherlight';
UPDATE expansionsets SET abbr = 'WWK' WHERE name = 'Worldwake';
UPDATE expansionsets SET abbr = 'ZEN' WHERE name = 'Zendikar';
